/**
 * ============================================================
 *  DATA.JS — Conteúdo do Portfólio do Laboratório
 * ============================================================
 *
 *  ESTE É O ÚNICO ARQUIVO QUE VOCÊ PRECISA EDITAR.
 *
 *  Para adicionar um novo projeto:
 *    1. Copie um dos blocos abaixo (entre { ... })
 *    2. Cole ao final da lista (antes do ];)
 *    3. Preencha os campos
 *    4. Salve — o site atualiza automaticamente.
 *
 * ============================================================
 */

// ── INFORMAÇÕES GERAIS DO LABORATÓRIO ─────────────────────
const LAB = {
  sigla:         "LACOP",
  nomeCompleto:  "Laboratório de Comunicaçãoes Ópticas, Sensores e Instrumentação",
  universidade:  "Universidade Federal Fluminense — Departamento de Engenharia de Telecomunicações",
  descricao:     "Laboratório de pesquisa aplicada em comunicações óticas, instrumentação e sensores para aplicações diversas.",
  email:         "viniciusnhs@id.uff.br",
  endereco:      "Rua Passo da Pátria, 156, Bloco E, Salas 413 e 307, São Doming, Niterói - RJ",
  // Métricas do hero (atualize manualmente)
  stats: {
    projetos:      14,
    pesquisadores: 10,
    publicacoes:   47,
    patentes:       6,
    parceiros:      8,
  },
};

// ── EQUIPE ─────────────────────────────────────────────────
//
//  Campos:
//    iniciais   — 2 letras usadas como fallback se não tiver foto (ex: "AS")
//    nome       — nome completo com título
//    cargo      — ex: "Coordenadora", "Doutorando", "Bolsista IC"
//    area       — frase curta descrevendo a linha de pesquisa
//    categoria  — "pesquisador" | "doutorando" | "mestrando" | "ic"
//    foto       — (OPCIONAL) caminho da foto ou URL externa
//    lattes     — (OPCIONAL) URL do currículo Lattes
//                 Ex: "https://lattes.cnpq.br/1234567890123456"
//
const EQUIPE = [
  {
    iniciais:  "VNHS",
    foto:      "fotos/vnhs.jpeg",
    nome:      "Prof. DSc. Vinicius Nunes Henrique Silva",
    cargo:     "Pesquisador Associado",
    area:      "Comunicações ópticas sem fio, instrumentação e sensores.",
    categoria: "pesquisador",
    lattes:    "http://lattes.cnpq.br/4252574634164456",
  },
  {
    iniciais:  "APLB",
    foto:      "fotos/aplb.jpg",
    nome:      "Prof. DSc. Andrés Pablo Lopez Barbero (full professor)",
    cargo:     "Pesquisador Sênior",
    area:      "Instrumentação fotônica e interrogação de sensores a fibra.",
    categoria: "pesquisador",
    lattes:    "http://lattes.cnpq.br/8904044191613796",
  },
  {
    iniciais:  "RMR",
    foto:      "fotos/rmr.jpg",
    nome:      "Prof. DSc. Ricardo Marques Ribeiro",
    cargo:     "Pesquisador Sênior",
    area:      "Comunicações ópticas em meios confinados",
    categoria: "pesquisador",
    lattes:    "http://lattes.cnpq.br/4362724287992760",
  },
  {
    iniciais:  "HJK",
    foto:      "fotos/hjk.jpg",
    nome:      "Prof. DSc. Hypolito José Kalinowski (full professo)",
    cargo:     "Pesquisador Sênior",
    area:      "Sensores ópticos",
    categoria: "pesquisador",
    lattes:    "http://lattes.cnpq.br/6560372925252581",
  },
  {
    iniciais:  "TAMGF",
    foto:      "fotos/beatriz-torres.jpg",
    nome:      "Profa. DSc. Taiane Alvarenga Menandro Garcia de Freitas",
    cargo:     "Pesquisadora Adjunta",
    area:      "Não-linearidades em sistemas WDM e compensação digital.",
    categoria: "pesquisador",
    lattes:    "http://lattes.cnpq.br/9280916823481414",
  },
  {
    iniciais:  "MAG",
    foto:      "fotos/mag.png",
    nome:      "MSc. Márcio Alexandre Dias Garrido",
    cargo:     "Doutorando",
    area:      "Sistemas de comunicações ópticas em espaço livre",
    categoria: "doutorando",
    lattes:    "http://lattes.cnpq.br/7310316924480839",
  },
  {
    iniciais:  "AACB",
    foto:      "fotos/aacb.jpg",
    nome:      "MSc. Antonio Adade de Castro Batista",
    cargo:     "Doutorando",
    area:      "Sistemas de comunicações ópticas sem fio no visível",
    categoria: "doutorando",
    lattes:    "http://lattes.cnpq.br/5089574113301481",
  },
  {
    iniciais:  "TDA",
    foto:      "fotos/tda.jpg",
    nome:      "MSc. Tiago Duarte Amorim",
    cargo:     "Doutorando",
    area:      "Sistemas de comunicações ópticas sem fio no visível",
    categoria: "doutorando",
    lattes:    "http://lattes.cnpq.br/9139738182304749",
  },
    {
    iniciais:  "MSS",
    foto:      "fotos/mss.jpg",
    nome:      "MSc. Matheus de Souza Santos",
    cargo:     "Doutorando",
    area:      "Sistemas de comunicações ópticas sem fio no espaço livre",
    categoria: "doutorando",
    lattes:    "https://lattes.cnpq.br/0000000000000007",
  },
  {
    iniciais:  "JP",
    foto:      "fotos/joao-pedro.jpg",
    nome:      "João Pedro Lima",
    cargo:     "Bolsista IC",
    area:      "Caracterização de componentes ópticos passivos.",
    categoria: "ic",
    lattes:    "https://lattes.cnpq.br/0000000000000008",
  },
];

// ── PUBLICAÇÕES ────────────────────────────────────────────
//
//  Campos:
//    titulo   — título completo do artigo
//    autores  — autores no formato "Sobrenome, I.; ..."
//    veiculo  — nome do periódico/conferência + DOI
//    ano      — ano de publicação (número)
//
const PUBLICACOES = [
  {
    titulo:  "Machine learning algorithms for triangulation-based optical beam tracking in FSO systems",
    autores: "H.B., B.F.; A., G.M.; P.L., B.A.; N., F.T.; Silva, V.N.H.",
    veiculo: " · DOI: 10.1016/j.optlaseng.2025.109397",
    ano:     2026,
  },
  {
    titulo:  "Assessing functional diversity and composition using multispectral images in Atlantic Forest restoration sites",
    autores: "AYRES, D.O.J.; AMORIM, D.F.O.Â.M.; QUINTÃO, D.A.A.; TORRES, D.A.C.; BASTOS, G.E.; Silva, V.N.H.; DUARTE, D.M.L.F.; BASTOS, L.G.; BARRETO, S.J.B.",
    veiculo: " · DOI: 10.1111/rec.70310",
    ano:     2026,
  },
  {
    titulo:  "Hop Essential Oils: Multivariate Hydrodistillation Optimization and GC-MS Characterization",
    autores: "SILVA, A.R.; FERRARI, Q.B.C.; CUNHA, P.F.; ALCOFORADO, S.L.; Silva, V.N.H.; MATTOS, D.L.; CARVALHO, M.F.F.D.",
    veiculo: " · DOI: 10.1021/acsfoodscitech.5c01075",
    ano:     2026,
  },
  {
    titulo:  "Sum-Rate Maximization in Massive MIMO with Joint Antenna Selection and Power Allocation",
    autores: "Gois, J.N.; Silva, M.d.S.P.; Silva, V.N.H.; Ferreira, T.N.",
    veiculo: " · DOI: 10.21528/lnlm-vol23-no1-art1",
    ano:     2025,
  },
  {
    titulo:  "New approach to estimate sensible heat flux through optical triangulation",
    autores: "Garrido, M.A.D.; Lyra, G.B.; Zeri, M.; HAJJAR, H.A.; Barbero, A.P.L.; Silva, V.N.H.",
    veiculo: " · DOI: 10.1016/j.measurement.2025.116655",
    ano:     2025,
  },
  {
    titulo:  "Modeling of Data Transmission in Polymer Optical Fibers Using DMT and Machine Learning Techniques",
    autores: "Gois, J.N.; Sampaio, F.A.N.; Haddad, D.B.; Neto, L.A.; Silva, V.N.H.; Ferreira, T.N.",
    veiculo: " · DOI: 10.1002/mop.70109",
    ano:     2025,
  },
  {
    titulo:  "Analysis of sugar distributions in barley wort saccharification via Capillary Electrophoresis",
    autores: "Aredes, R.; Peixoto, F.C.; Sphaier, L.A.; Silva, V.N.H.; Duarte, L.M.; Marques, F.F.d.C.",
    veiculo: " · DOI: 10.1021/acsfoodscitech.4c00696",
    ano:     2025,
  },
  {
    titulo:  "Mitigation of Pointing Errors in FSO Systems Through AI-Driven Spatial Light Modulation",
    autores: "B., B.F.; F., C.V.; M., F.G.; L., B.A.; P., M.P.; P., G.F.; Silva, V.N.H.",
    veiculo: " · DOI: 10.1109/lpt.2025.3575366",
    ano:     2025,
  },
  {
    titulo:  "Enhancing Noise Resilience of CE-OFDM in Visible Light Communication Systems",
    autores: "R., R.B.M.S.; Silva, V.N.H.; P., M.P.; R., M.M.C.",
    veiculo: " · DOI: 10.1109/LPT.2025.3577779",
    ano:     2025,
  },
  {
    titulo:  "Enhanced Photodetector Field of View for IoT-Driven VLC Systems Using Fluorescent Optical Antennas",
    autores: "C., B.A.A.; D., A.T.; M., R.R.; L., B.A.P.; B., D.R.R.; C., P.F.; Silva, V.N.H.",
    veiculo: " · DOI: 10.1109/ACCESS.2025.3593261",
    ano:     2025,
  },
  {
    titulo:  "Material Classification Using Optical Wireless Communications Data and Machine Learning",
    autores: "ADRIANE, D.; AMARO, L.; MICHEL, T.; MARIA, M.; Silva, V.N.H.; FELIPE, H.",
    veiculo: "2025 IEEE 16th Latin America Symposium on Circuits and Systems (LASCAS)",
    ano:     2025,
  },
  {
    titulo:  "Coating of microfibrillated cellulose on plastic optical fiber",
    autores: "GUILHERME, D.É.; LAVINNE, F.D.Q.I.; ISABELA, R.M.; PABLO, L.B.A.; ISABEL, B.R.N.; Silva, V.N.H.",
    veiculo: "29th International Conference on Optical Fiber Sensors",
    ano:     2025,
  },
  {
    titulo:  "Experimental Evaluation of FSO Link: Impact of Pointing Error on OFDM System Performance",
    autores: "D., E.G.; D., G.M.A.; L., B.A.P.; GUSTAVO, B.L.; V., C.T.; Silva, V.N.H.",
    veiculo: "2025 IEEE International Instrumentation and Measurement Technology Conference (I2MTC)",
    ano:     2025,
  },
  {
    titulo:  "Influence of LOS and NLOS Components in an Indoor VLC-RSMA System",
    autores: "D., A.T.; Silva, V.N.H.; Renna, R.B.D.",
    veiculo: "2025 International Conference on Optical Network Design and Modeling (ONDM)",
    ano:     2025,
  },
  {
    titulo:  "Modulation Strategies for Robust Optical Wireless Communications and Sensing in 6G",
    autores: "M.S.R., R.B.; Silva, V.N.H.; P., M.P.; R., M.M.C.",
    veiculo: "2025 25th Anniversary International Conference on Transparent Optical Networks (ICTON)",
    ano:     2025,
  },
  {
    titulo:  "Inter-symbol and Multi-user Interference Cancellation for LEO Satellite Systems",
    autores: "F, S.F.; VICTOR, F.; G., G.A.; Silva, V.N.H.; DI, R.R.B.",
    veiculo: "XLIII Simpósio Brasileiro de Telecomunicações e Processamento de Sinais",
    ano:     2025,
  },
  {
    titulo:  "Temporal Analysis of Commercially Available Fluorescent Plastic Optical Fibers Intended for VLC Applications",
    autores: "Maia, B.F.C.B.; Pinheiro, I.L.d.C.; Ferreira, V.T.; Silva, V.N.H.; Vieira, P.; Andrade, J.R.M.d.; Ribeiro, R.M.",
    veiculo: "The 33rd International Conference on Plastic Optical Fibers",
    ano:     2025,
  },
  {
    titulo:  "Preliminary Construction of Microfibrillated Cellulose-Based Biofilms Functionalized with Colorimetric Indicators for Fiber-Optic Calcium Sensing",
    autores: "Ramírez, N.I.B.; Silva, M.C.d.; Ribeiro, R.S.d.A.; Jupy, A.B.; Silva, V.N.H.",
    veiculo: "Congresso Brasileiro de Engenharia Química e Encontro Brasiliero sobre o Ensino de Engenharia Química",
    ano:     2025,
  },
  {
    titulo:  "AI-Driven Atmospheric Turbulence Compensation and Channel Modeling in FSO Systems",
    autores: "B., B.F.; M., F.G.; L., B.A.; P., M.P.; P., G.F.; Silva, V.N.H.",
    veiculo: "2025 SBFoton International Optics and Photonics Conference (SBFoton IOPC)",
    ano:     2025,
  },
  {
    titulo:  "Adaptive Inter-Symbol and Multi-User Interference Cancellation for OTFS in LEO SATCOM",
    autores: "F., S.F.; VICTOR, F.; Silva, V.N.H.; B., D.R.R.",
    veiculo: "2025 SBMO/IEEE MTTS International Microwave and Optoelectronics Conference (IMOC)",
    ano:     2025,
  },
  {
    titulo:  "Naval Radar Co-Site EMI Mitigation with a Novel Absorber Metamaterial",
    autores: "A., T.M.D.; B., D.R.R.; MAURÍCIO, W.; Silva, V.N.H.",
    veiculo: "2025 SBMO/IEEE MTTS International Microwave and Optoelectronics Conference (IMOC)",
    ano:     2025,
  },
  {
    titulo:  "Transmission Channel Characterization Using LoRa Device in an Industrial Environment",
    autores: "V., L.M.C.; Silva, V.N.H.; B., S.M.W.; G., C.P.V.; N., F.T.",
    veiculo: "2025 SBMO/IEEE MTTS International Microwave and Optoelectronics Conference (IMOC)",
    ano:     2025,
  },
  {
    titulo:  "Heat and mass transfer with chemical kinetics in alcoholic fermentation of multiple sugars: Lumped formulation and dimensional analysis",
    autores: "Pinheiro, I.F.; Serrano, H.L.; Sphaier, L.A.; Peixoto, F.C.; Silva, V.N.H.",
    veiculo: " · DOI: 10.1016/j.jfoodeng.2023.111863",
    ano:     2024,
  },
  {
    titulo:  "Análise de Endurecimento do Canal e Propagação Favorável em Sistemas MIMO Massivo",
    autores: "Silva, M.d.S.P.; Silva, V.N.H.; Gois, J.N.; Ferreira, T.N.",
    veiculo: "Congresso Brasileiro de Automática",
    ano:     2024,
  },
  {
    titulo:  "Performance of Commercially Available Fluorescent Plastic Optical Fibre Intended to be an ?Optical Antenna?",
    autores: "Maia, B.F.C.B.; Pinheiro, I.L.d.C.; Silva, V.N.H.; Toledo, A.; Ribeiro, R.M.",
    veiculo: "32nd International Conference on Plastic Optical Fibers",
    ano:     2024,
  },
  {
    titulo:  "An Optoeletronic Oscillator Based on Plastic Optical Fiber for Didactic Purpose",
    autores: "Ferreira, V.T.; Andrade, J.R.M.d.; Magri, V.P.R.; Santos, P.A.M.d.; Silva, V.N.H.; Ribeiro, R.M.",
    veiculo: "The 32nd International Conference on Plastic Optical Fibers",
    ano:     2024,
  },
  {
    titulo:  "Determination of carbohydrates in brewer's wort by capillary electrophoresis with indirect UV detection",
    autores: "Aredes, R.S.; Peixoto, F.C.; Sphaier, L.A.; Silva, V.N.H.; Duarte, L.M.; Marques, F.F.d.C.",
    veiculo: " · DOI: 10.1016/j.jfca.2023.105321",
    ano:     2023,
  },
  {
    titulo:  "Neglected frequencies analysis on switching operations in extra-high voltage electrical power substations",
    autores: "B, B.F.H.; L, B.A.P.; HUGO, F.V.; B, D.S.A.; S, D.S.D.; COSTA, P.A.D.; Silva, V.N.H.",
    veiculo: " · DOI: 10.1016/j.epsr.2023.109848",
    ano:     2023,
  },
  {
    titulo:  "Extreme Gradient Boost Regression to Model a SI-POF Link Using OFDM Transmission",
    autores: "N., G.J.; N., S.F.A.; N., F.T.; Silva, V.N.H.; L., B.A.P.; ANET, N.L.",
    veiculo: "2023 International Conference on Optical MEMS and Nanophotonics (OMN) and SBFoton International Optics and Photonics Conference (SBFoton IOPC)",
    ano:     2023,
  },
  {
    titulo:  "Interrogation Technique Using Harmonic Equations in the Electrical Domain for Long Period Grating Sensors",
    autores: "Silva, V.N.H.; ALVES, D.O.V.; WEBER, D.S.G.F.; BESSA, D.S.A.; LOPEZ, B.A.P.; CASCARDO, C.A.",
    veiculo: "2023 SBMO/IEEE MTTS International Microwave and Optoelectronics Conference (IMOC)",
    ano:     2023,
  },
  {
    titulo:  "Acoustic Data Communication Over a Stainless Metallic Rod",
    autores: "S., Z.W.; C., C.A.; Silva, V.N.H.; N., F.T.; L., B.A.P.",
    veiculo: "2023 SBMO/IEEE MTTS International Microwave and Optoelectronics Conference (IMOC)",
    ano:     2023,
  },
  {
    titulo:  "Performance of SMD-LED Array for Visible Light Communications",
    autores: "MARQUES, R.R.; BUCKINGHAM, M.B.F.C.; CHAGAS, P.I.L.D.; TOLEDO, S.A.C.D.; Silva, V.N.H.; BARUCKE, M.C.",
    veiculo: "XLI Simpósio Brasileiro de Telecomunicações e Processamento de Sinais",
    ano:     2023,
  },
  {
    titulo:  "Frequency Response of a Fluorescent Fibre Detector Intended for Visible Light Communications",
    autores: "MARQUES, R.R.; CHAGAS, P.I.L.D.; BUCKINGHAM, M.B.F.C.; MARISTELA, C.; BARUCKE, M.C.; Silva, V.N.H.",
    veiculo: "XLI Simpósio Brasileiro de Telecomunicações e Processamento de Sinais",
    ano:     2023,
  },
  {
    titulo:  "Low Complexity Algorithm for Antenna Selection using Hierarchical Matching Pursuit",
    autores: "JONATHAN, G.; Silva, V.N.H.; TADEU, F.",
    veiculo: "XLI Simpósio Brasileiro de Telecomunicações e Processamento de Sinais",
    ano:     2023,
  },
  {
    titulo:  "Entropy loading for capacity maximization of RGB-based visible light communications",
    autores: "A., L.P.; Silva, V.N.H.; R., M.M.C.; P., G.F.; P., M.P.",
    veiculo: " · DOI: 10.1364/OE.465195",
    ano:     2022,
  },
  {
    titulo:  "A fuzzy approach to LPFG-based optical sensor processing and interrogation",
    autores: "OLIVEIRA, B.F.; Aguiar, E.P.D.; Honório, L.d.M.; Silva, V.N.H.; Barbero, A.P.L.; Santos, A.B.d.",
    veiculo: " · DOI: 10.1109/TIM.2022.3216390",
    ano:     2022,
  },
  {
    titulo:  "Joint Optical Wireless Communication and Localization Using OFDM",
    autores: "B., M.E.; Silva, V.N.H.; P., M.P.; R., M.M.C.",
    veiculo: " · DOI: 10.1109/LPT.2022.3186734",
    ano:     2022,
  },
  {
    titulo:  "Performance of MMSE-LE in 2 Gbaud/s Single Carrier Visible Light Communication using PAM-2",
    autores: "ANDRE, N.S.F.; TADEU, F.; LUIZ, A.N.; PABLO, L.B.A.; MARIA, D.C.R.M.; Silva, V.N.H.",
    veiculo: "2022 13th International Symposium on Communication Systems, Networks and Digital Signal Processing (CSNDSP)",
    ano:     2022,
  },
  {
    titulo:  "Modeling the Bias Current and OFDM Signal Power under Amplitude Constraints for SI-POF",
    autores: "N., G.J.; N., T.J.; N., S.F.A.; N., F.T.; L., B.A.P.; Silva, V.N.H.; ANET, N.L.",
    veiculo: "2022 IEEE LatinAmerican Conference on Communications (LATINCOM)",
    ano:     2022,
  },
  {
    titulo:  "Loading Condition Estimation Using Long-Period Fiber Grating Array",
    autores: "OLIVEIRA, B.F.; RENATO, F.; DEIVID, C.; Silva, V.N.H.; P., L.A.; LEONARDO, D.M.H.; DOS, S.A.B.",
    veiculo: " · DOI: 10.1109/jsen.2020.3042779",
    ano:     2021,
  },
  {
    titulo:  "Dynamic Evolution of Bitterness Units in Beer Worts: Modeling and Concerns",
    autores: "Nascimento, I.C.d.; Calado, L.S.; Bojorge, N.; Silva, V.N.H.; Peixoto, F.C.",
    veiculo: "",
    ano:     2021,
  },
  {
    titulo:  "Modelling of an Optical Access Network Platform for Radio-Frequency Transmission in the S Band / Modelação de uma Plataforma de Rede de Acesso Óptico para Transmissão de Radiofrequências na Banda S",
    autores: "NOGUEIRA, S.F.A.; SANTOS, A.P.; Silva, V.N.H.; NAGASHIMA, F.T.; LUIZ, A.N.; GASPAR, G.A.; RIBEIRO, M.V.P.; LÓPEZ, B.A.P.",
    veiculo: " · DOI: 10.34117/bjdv7n8-227",
    ano:     2021,
  },
  {
    titulo:  "Optical Inclinometer Based on a LPG-Taper Series Configuration",
    autores: "LUIZ, F.F.R.; DOS, S.A.B.; LÓPEZ, B.A.P.; Silva, V.N.H.",
    veiculo: " · DOI: 10.1590/2179-10742021v20i3254754",
    ano:     2021,
  },
  {
    titulo:  "A Point-to-Multi-Point Tracking System for FSO Communication",
    autores: "KIRAN, K.V.; JAYASHREE, P.; KUMAR, T.A.; Silva, V.N.H.; SUDHAN, M.; KUMAR, D.S.",
    veiculo: " · DOI: 10.1109/tim.2021.3115202",
    ano:     2021,
  },
  {
    titulo:  "Real-Time Fermentation Monitoring of Synthetic Beer Wort Using Etched Fiber Bragg Grating",
    autores: "A., D.O.V.; L., B.A.P.; A., S.L.; B., D.S.A.; C., P.F.; Silva, V.N.H.",
    veiculo: " · DOI: 10.1109/tim.2021.3117051",
    ano:     2021,
  },
  {
    titulo:  "Etched Fiber Bragg Grating Probe using a Regular CNC Machine and a 3D Printer",
    autores: "VICENTE, O.; ALEXANDER, C.; ALEXANDRE, S.; Andres, B.; FERNANDO, P.; Silva, V.N.H.",
    veiculo: " · DOI: 10.1364/ao.439995",
    ano:     2021,
  },
  {
    titulo:  "Sondagem em Faixa Estreita e Modelagem de Canal de Propagação Urbano na Faixa de 3,5 GHz",
    autores: "TALITA, C.; Fonseca, F.J.B.d.; Ferreira, T.N.; Matos, L.J.d.; Silva, V.N.H.",
    veiculo: "",
    ano:     2021,
  },
  {
    titulo:  "Antena de Fibra Óptica Plástica como Detectora em Enlaces LiFi",
    autores: "DE, P.J.; MARQUES, R.R.; BARUCKE, M.C.; MARISTELA, C.; Silva, V.N.H.",
    veiculo: "XXXIX Simpósio Brasileiro de Telecomunicações e Processamento de Sinais",
    ano:     2021,
  },
  {
    titulo:  "Development of a capillary electrophoresis method for determination of carbohydrates in wort samples",
    autores: "Aredes, R.S.; Peixoto, F.C.; Sphaier, L.A.; Silva, V.N.H.; Duarte, L.M.; Marques, F.F.d.C.",
    veiculo: "Latin-American Symposium on Biotechnology, Biomedical, Biopharmaceutical, and Industrial Applications of Capillary Electrophoresis and Microchip Technology",
    ano:     2021,
  },
  {
    titulo:  "Optical Triangulation for Free-Space Optics Beam Tracking using Artificial Neural Networks",
    autores: "Bittar, F.H.B.; Garrido, M.A.D.; Nascimento, J.R.d.; BESSA, D.S.A.; Barbero, A.P.L.; Silva, V.N.H.",
    veiculo: "International Symposium on Optomechatronic Technology",
    ano:     2021,
  },
  {
    titulo:  "Simulation and Fabrication of a Low-Cost RFID Reader",
    autores: "L., G.M.V.; P., B.L.; R., M.V.P.; N., F.T.; J., D.M.L.; Silva, V.N.H.",
    veiculo: "2021 IEEE MTTS Latin America Microwave Conference (LAMC)",
    ano:     2021,
  },
  {
    titulo:  "A Mathematical Model for the Interrogation of LPG Fiber Optical Sensors Based on Electrical Harmonic Analysis",
    autores: "XAVIER, N.P.; C., C.A.; P., L.A.; Silva, V.N.H.; M., R.R.; BESSA, D.S.A.",
    veiculo: " · DOI: 10.1109/jsen.2019.2963275",
    ano:     2020,
  },
  {
    titulo:  "High Accuracy Homodyne Interferometric Method for Wide Dynamic Range Applications",
    autores: "C., C.A.; P., L.A.; Silva, V.N.H.; CLAUDIO, K.; H., G.J.; BESSA, D.S.A.",
    veiculo: " · DOI: 10.1109/jsen.2019.2961934",
    ano:     2020,
  },
  {
    titulo:  "Low-Cost Device to Measure Concentration of Saccharomyces cerevisiae</i> Through Methylene Blue Reduction",
    autores: "BESERRA, D.F.R.; Silva, V.N.H.; TREMMEL, M.V.; DOS, S.O.B.; MADALENA, D.A.C.Y.; BATISTA, F.S.",
    veiculo: " · DOI: 10.1109/tim.2019.2923486",
    ano:     2020,
  },
  {
    titulo:  "Correlated Time-Series in Multi-Day-Ahead Streamflow Forecasting Using Convolutional Networks",
    autores: "O., B.F.; Silva, V.N.H.; P., L.A.; LEONARDO, D.M.H.; DOS, S.A.B.",
    veiculo: " · DOI: 10.1109/access.2020.3040942",
    ano:     2020,
  },
  {
    titulo:  "Detecção de Fase Ótica em Interferômetos Homódinos Passivos Usando o Método Jn/Jn+2",
    autores: "Cascardo, A.; Junior, V.L.; CLAUDIO, K.; Galeti, J.H.; Barbero, A.P.L.; Silva, V.N.H.; Ribeiro, R.M.",
    veiculo: "MOMAG 2020",
    ano:     2020,
  },
  {
    titulo:  "Extensão do Método de Triangulação de Potências para Rastreamento de Feixe Ótico em Enlaces FSO",
    autores: "Nascimento, J.R.d.; Bittar, F.H.B.; Garrido, M.A.D.; Filho, W.d.S.G.; Barbero, A.P.L.; Silva, V.N.H.",
    veiculo: "MOMAG 2020",
    ano:     2020,
  },
  {
    titulo:  "Desenvolvimento de um protótipo de Mixer para aplicações na banda S",
    autores: "Sampaio, F.A.N.; Morais, E.R.; Coelho, V.B.; Silva, V.N.H.; Magri, V.P.R.; Ferreira, T.N.",
    veiculo: "MOMAG 2020",
    ano:     2020,
  },
  {
    titulo:  "Receptor de Comunicações por Luz Visível (VLC) Usando Antena de Fibra Óptica Plástica",
    autores: "Batista, A.A.d.C.; Paula, J.O.d.; Barbero, A.P.L.; Leme, C.B.M.P.; Ribeiro, R.M.; Silva, V.N.H.",
    veiculo: "MOMAG 2020",
    ano:     2020,
  },
  {
    titulo:  "Modelling of Discrete Multi-Tone Transmissions over Dispersive Polymeric Optical Fibers",
    autores: "Silva, V.N.H.; Ferreira, T.N.; Sampaio, F.A.N.; Abreu, P.; Neto, L.A.; Barbero, A.P.L.; Ribeiro, R.M.",
    veiculo: "MOMAG 2020",
    ano:     2020,
  },
  {
    titulo:  "Características Optoeletrônicas de Lasers de Diodo Verdes",
    autores: "Marins, F.A.; Silva, V.N.H.; Leme, C.B.M.P.; Ribeiro, R.M.",
    veiculo: "MOMAG 2020",
    ano:     2020,
  },
  {
    titulo:  "Estudo da Transmissão de Frequências Intermediárias (IFs) sobre Fibras Ópticas Plásticas",
    autores: "Marins, F.A.; Silva, V.N.H.; Correia, M.; Ribeiro, R.M.",
    veiculo: "MOMAG 2020",
    ano:     2020,
  },
  {
    titulo:  "Modeling Mass Ttransfer Through a Porous Medium of a Recirculating Mash System",
    autores: "Santos, J.; Sphaier, L.A.; Peixoto, F.C.; Silva, V.N.H.",
    veiculo: "18th Brazilian Congress of Thermal Sciences and Engineering",
    ano:     2020,
  },
  {
    titulo:  "Ajustes Alternativos para Perdas de Percurso em Sondagem Urbana na Faixa de 3,5 GHz",
    autores: "TALITA, C.; FÁBIO, F.; TADEU, F.; Silva, V.N.H.; LENI, M.; PEDRO, C.",
    veiculo: "XXXVIII Simpósio Brasileiro de Telecomunicações e Processamento de Sinais",
    ano:     2020,
  },
];

// ── PROJETOS ───────────────────────────────────────────────
const PROJETOS = [
  {
    id:          "p1",
    titulo:      "Desenvolvimento de uma Rede Inteligente Utilizando Cabos Ópticos no Combate às Perdas",
    status:      "completed",
    tipo:        "rd",
    periodo:     "2008–2009",
    resumo:      "Desenvolvimento de transceptores ópticos e cabos híbridos especiais destinados a condução de energia, comunicação e sensoriamento em redes de distribuição de energia elétrica.",
    descricao:   "Desenvolvimento de transceptores ópticos e cabos híbridos especiais destinados a condução de energia, comunicação e sensoriamento em redes de distribuição de energia elétrica.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Ampla Energia e Serviços",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Ribeiro, Ricardo M.", "Barbero, Andrés P. L. (Coordenador)", "Odair da Silva Xavier", "Yanes Checcacci Balod", "Henrique O. Henriques"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p2",
    titulo:      "Sistema de Previsão de Falhas em Redes Subterrâneas",
    status:      "completed",
    tipo:        "rd",
    periodo:     "2008–2009",
    resumo:      "Desenvolvimento de uma rede de sensores de parâmetros físicos, com o intuito de prever falhas em equipamentos contidos em galerias subterrâneas das redes de distribuição de energia elétrica.",
    descricao:   "Desenvolvimento de uma rede de sensores de parâmetros físicos, com o intuito de prever falhas em equipamentos contidos em galerias subterrâneas das redes de distribuição de energia elétrica.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "LIGHT Serviços de Eletricidade",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Ribeiro, Ricardo M. (Coordenador)", "Barbero, Andrés P. L.", "Henrique O. Henriques"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p3",
    titulo:      "Sistema Identificador de Áreas de Furto de Energia Elétrica",
    status:      "completed",
    tipo:        "rd",
    periodo:     "2008–2009",
    resumo:      "Desenvolvimento de uma rede de comunicação sem-fio no padrão WiMax e WiFi destinada a identificar áreas onde ocorram furtos de energia elétrica.",
    descricao:   "Desenvolvimento de uma rede de comunicação sem-fio no padrão WiMax e WiFi destinada a identificar áreas onde ocorram furtos de energia elétrica.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "LIGHT Serviços de Eletricidade",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Ribeiro, Ricardo M.", "Barbero, Andrés P. L. (Coordenador)", "Jorge Ângelo Mitrione Souza", "Henrique O. Henriques"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p4",
    titulo:      "Bastão Amperímetro para Detecção de Fraudes em Instalações Consumidoras de Baixa Tensão",
    status:      "completed",
    tipo:        "rd",
    periodo:     "2008–2009",
    resumo:      "Desenvolvimento de instrumentação de campo baseada em tecnologia óptica e RF para medição de consumo de energia residencial.",
    descricao:   "Desenvolvimento de instrumentação de campo baseada em tecnologia óptica e RF para medição de consumo de energia residencial.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "LIGHT Serviços de Eletricidade",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Ribeiro, Ricardo M.", "Barbero, Andrés P. L. (Coordenador)", "Odair da Silva Xavier", "Henrique O. Henriques"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p5",
    titulo:      "Desenvolvimento Experimental de Comunicações Ópticas em Distâncias Curtas e Fusão com Bluetooth",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2006–2009",
    resumo:      "Implementação de infraestrutura laboratorial para a realização de pesquisas e desenvolvimentos tecnológicos focados (no âmbito da proposta original) em fibras ópticas plásticas aplicadas a comunicação",
    descricao:   "Implementação de infraestrutura laboratorial para a realização de pesquisas e desenvolvimentos tecnológicos focados (no âmbito da proposta original) em fibras ópticas plásticas aplicadas a comunicação. O Projeto visa também o desenvolvimento de componentes, técnicas de caracterização. sistemas e enlaces de comuncação envolvendo as fibras ópticas plásticas.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Conselho Nacional de Desenvolvimento Científico e Tecnológico",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Ribeiro, Ricardo M. (Coordenador)", "Barbero, Andrés P. L.", "Paulo Acioly Marques dos Santos", "Odair da Silva Xavier", "Jorge Ângelo Mitrione Souza", "Yanes Checcacci Balod", "Sydney Bragantine Germano", "Luiz Anet Neto"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p6",
    titulo:      "Laboratório de Comunicações Ópticas em Distâncias Curtas - Tecnologia de Fibras Ópticas Plásticas",
    status:      "completed",
    tipo:        "rd",
    periodo:     "2006–2008",
    resumo:      "Trata-se da implantação de um Laboratório de desenvolvimento tecnológico de comunicações ópticas de alta capacidade em distâncias curtas com base nas fibras ópticas plásticas (POFs) e a fusão com outr",
    descricao:   "Trata-se da implantação de um Laboratório de desenvolvimento tecnológico de comunicações ópticas de alta capacidade em distâncias curtas com base nas fibras ópticas plásticas (POFs) e a fusão com outras tecnologias correlatas. O foco é o desenvolvimento de componentes passivos/ativos e a construção de enlaces multicanais para uso nas mais diversas demandas de setores de Telecomunicações, Informática, Energia Elétrica, Petróleo, etc.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Conselho Nacional de Desenvolvimento Científico e Tecnológico; Fundação Carlos Chagas Filho de Amparo à Pesquisa do Estado do RJ; Pontifícia Universidade Católica do Rio de Janeiro",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Ribeiro, Ricardo M. (Coordenador)", "Barbero, Andrés P. L.", "Paulo Acioly Marques dos Santos", "Odair da Silva Xavier", "Jorge Ângelo Mitrione Souza", "Yanes Checcacci Balod"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p7",
    titulo:      "Cooperação Científica e Tecnológica entre Brasil e França para o Desenvolvimento e Transferência de Tecnologia de Cristais Líquidos para Aplicações em diversas Aéreas do Conhecimento",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2013–2016",
    resumo:      "Desde o início do programa de doutoramento de Vinícius Nunes Henrique, em 2009 no Département d?Optique da Telecom Bretagne e até o presente momento, a colaboração entre os dois laboratórios tem sido ",
    descricao:   "Desde o início do programa de doutoramento de Vinícius Nunes Henrique, em 2009 no Département d?Optique da Telecom Bretagne e até o presente momento, a colaboração entre os dois laboratórios tem sido a de construir dispositivos de cristais líquidos colestéricos na instituição francesa e a sua caracterização óptica no LaCOp/UFF para aplicações em redes de comunicações baseadas em fibras ópticas poliméricas. Essa colaboração pode ser medida através de diversos trabalhos já publicados em conjunto . A partir de 2013, e com a obtenção do apoio financeiro aqui proposto, passaremos a desenvolver tais dispositivos na UFF, objetivando não somente aplicações em sistemas de comunicação, mas também para diversas áreas do conhecimento. Tal objetivo será alcançado através do desenvolvimento e transferência de tecnologia de criatais liquidos e que será possível graças ao repatriamento do jovem pesquisador Vinicius Nunes e ao apoio da equipe francesa. A solicitação está em coerência com uma das linhas de pesquisas do Laboratório de Comunicações Ópticas da UFF e do Curso de Mestrado em Engenharia de Telecomunicações da UFF, através da qual diversos alunos tem sido titulados nos últimos anos.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Não especificado",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Ribeiro, Ricardo M.", "Odair da Silva Xavier", "Sydney Bragantine Germano", "Andres Pablo Lopez Barbero (Coordenador)", "Laurent Dupont", "Daniel Stoenescu", "Jean-Louis de Bougrenet de la Tocanye", "Kedar Sathaye"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p8",
    titulo:      "Dispositivo de Visualização 2D e 3D para Guiamento e Controle de Veículos Aéreos não Tripulados para Planejamento e Execução de Missões de Vigilância",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2014–2015",
    resumo:      "A pesquisa tem como principal objetivo o de desenvolver um dispositivo de visualização misto, de 2D e 3D com três modos de operação: planejamento, simulação e execução de missões de vigilância de veíc",
    descricao:   "A pesquisa tem como principal objetivo o de desenvolver um dispositivo de visualização misto, de 2D e 3D com três modos de operação: planejamento, simulação e execução de missões de vigilância de veículos aéreos não tripulados (VANTS). O dispositivo em questão, em linhas gerais, permitirá: a) que dois operadores possam compartilhar uma visão em 3D de um mapa projetado em uma mesa transmissiva ou reflexiva de dois ângulos de visão diferentes; b) que os operadores possam interagir com o mapa, com os dedos, de forma a poder ampliá-lo e rotacioná-lo; c) que os mesmos possam simular e/ou executar o guiamento e o controle, também com os dedos no modo planejamento e com um joystick no modo simulação, de no mínimo um VANTs; d) e que possam visualizar o que os VANTs, munidos de câmeras filmadoras, estão filmando em duas dimensões através de uma segunda tela de projeção 2D. Acreditamos que o dispositivo a ser desenvolvido será um importante acessório dos VANTS, pois permitirá planejamento, simulação e execução de missões de vigilância: antiterrorismo, de guerrilha urbana e controle de fronteira.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "AGIR - Agência de Inovação PROPPi/UFF",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Ricardo Marque Ribeiro", "Andres Pablo Lopez Barbero", "Laísa Carvalho", "Cecília Machado Alves"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p9",
    titulo:      "Desenvolvimento de Equipamento de Baixo Custo para Comunicação Óptica Por Espaço Livre (FSO)",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2014–2015",
    resumo:      "Este projeto tem como objetivo específico desenvolver um protótipo comercial de um par transmissor/receptor FSO de baixo custo, o qual deverá ter características iguais ou superiores àquelas apresenta",
    descricao:   "Este projeto tem como objetivo específico desenvolver um protótipo comercial de um par transmissor/receptor FSO de baixo custo, o qual deverá ter características iguais ou superiores àquelas apresentadas por similares importados, visando atender as necessidades de comunicação banda larga do mercado nacional, aplicações militares e substituir enlaces de microondas em hospitais e/ou áreas sensíveis.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "AGIR - Agência de Inovação PROPPi/UFF",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "pablo lopez", "Ricardo Marque Ribeiro", "Rafael Albino", "Roberta Mesquita Silva"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p10",
    titulo:      "Telemetria para Serviços Fiber-to-the-Home",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2014–2016",
    resumo:      "Construção de uma plataforma básica FTTH. Medições de parâmetros típicos de redes. Telemetria com uso de Labview.",
    descricao:   "Construção de uma plataforma básica FTTH. Medições de parâmetros típicos de redes. Telemetria com uso de Labview.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Fundação Carlos Chagas Filho de Amparo à Pesquisa do Estado do RJ",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Ricardo Marque Ribeiro", "Andres Pablo Lopez Barbero", "Leni Joaquim de Matos", "Tadeu Nagashima Ferreira (Coordenador)", "Fábio José da Fonseca"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p11",
    titulo:      "Implementação de uma Linha de Pesquisa em Comunicação Óptica no Visível (VLC ? Visible Light Communication)",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2018–2019",
    resumo:      "O conceito de comunicação óptica sem fio (OWC ? Optical Wireless Communication), de uma forma abrangente, se refere a transmissão da informação pela modulação de feixe de luz visível, ou infravermelha",
    descricao:   "O conceito de comunicação óptica sem fio (OWC ? Optical Wireless Communication), de uma forma abrangente, se refere a transmissão da informação pela modulação de feixe de luz visível, ou infravermelha, pela atmosfera ou vácuo. A comunicação óptica no visível, mais conhecida como VLC (Visible Light Communication), é uma parte das redes OWC que operam no espectro da luz visível que compreende os comprimentos de ondas entre 400nm a 700nm. De acordo com a empresa MarketsandMarkets, a segunda maior empresa em publicações premiadas sobre o mercado industrial, o VLC e o FSO (Free Space Optics ? Óptica em Espaço Livre) terão, respectivamente, um crescimento de 87,31% e 44,93% de 2014 até o ano 2020. Embora a perspectiva de crescimento seja bastante favorável, no melhor do conhecimento do autor, não existe no mercado nacional nenhuma empresa que pesquise ou desenvolva produtos tanto em VLC quanto em FSO. Ao contrário, na Europa e nos Estados Unidos, observa-se um crescente investimento na área, tanto no meio acadêmico quanto no industrial. Por exemplo, pode-se citar o projeto OPTICWISE fundado pela European Science Foudation com o objetivo de criar uma plataforma interdisciplinar de pesquisa e desenvolvimento em OWC até 2015. Nesse contexto, esta proposta vem solicitar a FAPERJ o apoio financeiro para o professor doutor Vinicius Nunes Henrique Silva, recém contratado, iniciar um projeto de pesquisa que se propõe a implementar uma linha de pesquisa em OWC no Laboratório de Comunicação Óptica (LACOP) da Universidade Federal Fluminense e, a curto prazo, desenvolver um transceptor óptico operando no visível que poderá ser utilizando tanto para comunicação VLC quanto para FSO.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Fundação Carlos Chagas Filho de Amparo à Pesquisa do Estado do RJ",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Ricardo Marque Ribeiro", "Andres Pablo Lopez Barbero"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p12",
    titulo:      "Multiplexação OFDM em Fibras de Plástico utilizando Fonte Fluorescente em 560nm",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2015–2019",
    resumo:      "O projeto consiste na pesquisa e desenvolvimento de um transmissor de sinais OFDM&#10;(Orthogonal Frequency Division Multiplexing) para fibras plásticas multimodo plásticas&#10;(POF) de índice degrau ",
    descricao:   "O projeto consiste na pesquisa e desenvolvimento de um transmissor de sinais OFDM&#10;(Orthogonal Frequency Division Multiplexing) para fibras plásticas multimodo plásticas&#10;(POF) de índice degrau e gradual. A novidade desse projeto de pesquisa está em utilizar uma fibra fluorescente com emissão no comprimento de onda de 560nm (amarelo) com a intenção de aumentar a eficiência espectral dos sistemas de comunicação óptico em POFs. No melhor do nosso conhecimento, as fontes de luz existentes (LEDs e LASERS) que operam na região de menor atenuação das fibra de plástico, amarelo (560nm), não possuem concomitantemente os atributos necessárias, tais como: eye safety, tamanho, velocidade de modulação,?integrabilidade?, entre outros. As características dessas fibras fluorescentes, já publicadas em revista especializada do IEEE pelo coordenador do projeto [1], podem vir a aumentar a capacidade dos sistemas WDM (Wavelength Division Multiplexing) através do aumento do número de canais que hoje operam, predominantemente, no azul, no verde e no vermelho. Além disso, associado a uma modulação OFDM pode-se aumentar a largura de banda do canal pela atenuação do efeito de dispersão modal que é fator limitante das comunicações ópticas baseados em POF.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Não especificado",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Flávio André Nogueira Sampaio"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p13",
    titulo:      "Desenvolvimento de Equipamento Óptico de Baixo Custo para Contagem de Células de Leveduras",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2016–2018",
    resumo:      "A cerveja é produzida pela ação de leveduras sobre um meio de composição apropriada. Para cada tipo de cerveja há uma linhagem de levedura indicada. O processo é iniciado adicionando uma cultura pura ",
    descricao:   "A cerveja é produzida pela ação de leveduras sobre um meio de composição apropriada. Para cada tipo de cerveja há uma linhagem de levedura indicada. O processo é iniciado adicionando uma cultura pura da levedura escolhida, denominada inóculo. Ao final do processo essa quantidade de leveduras pode ou não ser reutilizada. O inóculo precisa ter uma quantidade de células vivas adequada, do contrário a fermentação da cerveja pode ser prejudicada. A medida do número de células vivas pelos cervejeiros artesanais não é realizada por falta de experiência e de equipamentos. Os equipamentos e técnicas disponíveis no mercado são poucas, trabalhosas e a maior parte de custo alto, inviabilizando essa análise para esses produtores. &#10;A ideia do projeto é o desenvolvimento de um equipamento de fácil operação para a determinação do número de células vivas no inóculo de um processo cervejeiro. O equipamento poderia ser usado por cervejeiros artesanais, sejam domésticos ou de pequenas fábricas. Considerando que o apreço por cervejas artesanais está em expansão, acredita-se que o equipamento será muito bem recebido pelo mercado.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Não especificado",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "vinicius tremmel maia", "Rodrigo Beserra", "Sorele Batista Fiaux", "Yanina Calvette"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p14",
    titulo:      "Monitoramento do Balanço de Energia e Captura de Carbono em Área de Reflorestamento",
    status:      "ongoing",
    tipo:        "academic",
    periodo:     "2017–atual",
    resumo:      "A mudança da cobertura da terra, tal como a perda de áreas vegetais, contribuem para o aumento da emissão de Gases de Efeito Estufa (GEE), assim como alterações no balanço de radiação e energia, levan",
    descricao:   "A mudança da cobertura da terra, tal como a perda de áreas vegetais, contribuem para o aumento da emissão de Gases de Efeito Estufa (GEE), assim como alterações no balanço de radiação e energia, levando à mudanças climáticas regionais e globais. Sendo assim, monitoramento das áreas de recuperação florestal faz-se necessário para o entendimento da dinâmica de transferência de energia e massa, bem como sua influência na fixação de carbono, na contribuição no ciclo hidrológico regional e nas emissões de GEE. Para mensurar as trocas de massa e balanço de energia são usados equipamentos comerciais como o Eddy Covariance ou o Scintollometer, que se utilizam de medidas da turbulência atmosférica associadas à informações de umidade do ar e concentração de gases para calcular os fluxos de calor latente, calor sensível e evapotranspiração de uma região. O objetivo deste projeto é o desenvolvimento de protótipo funcional capaz de medir turbulência e os fluxos de energia e massa, em uma área de 1,0 Km2, comparável a observações satélite, baseado em um equipamento previamente testado na Universidade Federal Fluminense.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Fundação Carlos Chagas Filho de Amparo à Pesquisa do Estado do RJ",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Ricardo Marque Ribeiro", "Carlos Rodrigues Pereira", "Gustavo Bastos Lyra"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p15",
    titulo:      "Desenvolvimento de um Dispositivo Baseado em Triangulação de Potências Ópticas para medição da Evapotranspiração em áreas de plantio/cultura",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2017–2020",
    resumo:      "Este projeto de caráter multidisciplinar visa principalmente o desenvolvimento de um protótipo de bancada para medidas de evapotranspiração (ET), utilizando a técnica de triangulação de potências ópti",
    descricao:   "Este projeto de caráter multidisciplinar visa principalmente o desenvolvimento de um protótipo de bancada para medidas de evapotranspiração (ET), utilizando a técnica de triangulação de potências ópticas. A medição da quantidade de água evaporada a partir do solo e da transpiração das plantas por triangulação óptica, no melhor do conhecimento dos autores, é inédita. As principais vantagens da técnica são: inferir a evapotranspiração através de medidas da divagação do feixe, que é mais intenso próximo ao solo, e ser mais sensível do que a técnica de medição utilizando cintilômetros. Além disso, o protótipo a ser desenvolvido e caracterizado é potencialmente mais simples e de menor custo que equipamentos comerciais com mesmo propósito.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Conselho Nacional de Desenvolvimento Científico e Tecnológico",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Ricardo Marque Ribeiro", "Gubio de Oliveira", "Andres Pablo Lopez Barbero", "Carlos Rodrigues Pereira"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p16",
    titulo:      "Sistemas óticos para telecomunicações",
    status:      "ongoing",
    tipo:        "academic",
    periodo:     "2017–atual",
    resumo:      "No contexto da linha de pesquisa, este projeto tem como o objetivo o desenvolvimento de soluções inovadoras contribuindo para o aumento da capacidade e melhor uso do espectro em sistemas de comunicaçõ",
    descricao:   "No contexto da linha de pesquisa, este projeto tem como o objetivo o desenvolvimento de soluções inovadoras contribuindo para o aumento da capacidade e melhor uso do espectro em sistemas de comunicações óticas, mediante novos conceitos, dispositivos e formatos de modulação para sistemas de comunicação ótica de longa distância baseados em fibras óticas de sílica, redes óticas de curta distância utilizando fibras ópticas poliméricas, rádio sobre fibra, comunicação ótica no espaço livre e comunicação por luz visível.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Não especificado",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Ricardo Marque Ribeiro", "Andres Pablo Lopez Barbero", "Hypolito José Kalinowski (Coordenador)"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p17",
    titulo:      "Dispositivos e componentes para comunicações óticas",
    status:      "ongoing",
    tipo:        "academic",
    periodo:     "2017–atual",
    resumo:      "As fibras óticas são conhecidas principalmente pela alta capacidade de transmitir informação. No entanto, essa capacidade encontra diversos gargalos nas aplicações sistêmicas devido a limites impostos",
    descricao:   "As fibras óticas são conhecidas principalmente pela alta capacidade de transmitir informação. No entanto, essa capacidade encontra diversos gargalos nas aplicações sistêmicas devido a limites impostos por outros componentes, particularmente aqueles de natureza eletrônica, limitados a frequências muito inferiores àquelas da portadora ótica. Alternativas para tais componentes podem ser obtidas por técnicas puramente óticas, ou combinando propriedades óticas não lineares de guias e fibras com materiais especiais. Amplificadores óticos são um exemplo clássico do uso de tais propriedades e hoje procuram-se elementos para otimizar a amplificação ótica em outras faixas do espectro, desde a banda-O até a região do visível. O projeto visa estudar materiais, guias de onda e dispositivos deles derivados com propriedades óticas ativas, interação ótica com campos eletromagnéticos ou acústicos em outras faixas de frequência e grandezas físico químicas envolvidas no processo. Como subproduto desse projeto têm-se também materiais e componentes para geração, distribuição e controle de energia dentro do conceito de smart grid, objetivos ligados à outra área de concentração do programa.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Não especificado",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Andres Pablo Lopez Barbero", "Ricardo Marque Ribeiro", "Hypolito José Kalinowski (Coordenador)"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p18",
    titulo:      "Sistema Sensor de Vazamentos de Óleo em Cabos OF",
    status:      "completed",
    tipo:        "rd",
    periodo:     "2018–2020",
    resumo:      "Este projeto visa otimizar a tecnologia desenvolvida no P&D 64/11, &quot;&quot; Tecnologia USTDR (Ultrasonic Time-Domain Reflectometer) para Detecção e Localização de Vazamento de Óleo Isolante em Lin",
    descricao:   "Este projeto visa otimizar a tecnologia desenvolvida no P&D 64/11, &quot;&quot; Tecnologia USTDR (Ultrasonic Time-Domain Reflectometer) para Detecção e Localização de Vazamento de Óleo Isolante em Linhas Subterrâneas de 138 kV&quot; e tornar o protótipo construido em cabeça de série para futura fabricação e comercialização.&#10;Os pulsos de ondas ultra-sônicas são refratados pelas descontinuidades do material, e são captados na outra extremidade por um transdutor também piezo-elétrico que transforma a onda ultra-sônica em um pulso elétrico, capaz de ser analisado por equipamentos eletrônicos.&#10;No equipamento eletrônico, através da análise na freqüência dos pulsos ultra-sônicos refratados, os obstáculos que provocaram tais refrações podem ser estimados, entre eles pequenos vazamentos de óleo, analisando a amplitude das frequências da onda refratada.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Não especificado",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Henrique O. Henriques (Coordenador)", "Andres Pablo Lopez Barbero", "Lucas de Souza de Oliveira", "Marcos da Rocha Vaz", "Vitor Hugo Ferreira"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p19",
    titulo:      "Instrumentação Ótica para Aplicações em Sensores e Telecomunicações",
    status:      "ongoing",
    tipo:        "academic",
    periodo:     "2018–atual",
    resumo:      "Dentre os trabalhos no laboratório sob a coordenação do proponente, os mais sensíveis a&#10;recursos financeiros são o desenvolvimento de: um medidor de evapotranspiração por&#10;triangulação de potên",
    descricao:   "Dentre os trabalhos no laboratório sob a coordenação do proponente, os mais sensíveis a&#10;recursos financeiros são o desenvolvimento de: um medidor de evapotranspiração por&#10;triangulação de potências óticas em colaboração com o Prof. Dr. Gustavo Lyra e Prof. Dr.&#10;Carlos Rodrigues da Pós-Graduação em Eng. de Biosistemas (PGEB); um contador de&#10;leveduras de simples operação baseado na taxa de redução do azul de metileno em colaboração&#10;com a Profa. Dra. Sorele Fiaux do PGEB; um medidor de amargor de cerveja no visível em colaboração com o Prof. Dr. Fernando Peixoto da Pós-Graduação em Eng. Química. Na linha de telecomunicações: aprimoramento de uma fonte ótica em 560 nm para comunicação de dados em enlaces em fibras ótica poliméricas (POF), desenvolvimento de multiplexadores e demultiplexadores no visível incluindo o canal em 560 nm e design de enlace Rádio Sobre Fibra em POF para ambiente celular 5G. Por fim, processamento de sinais para multiplexação ortogonal em frequências e formatos de modulação avançado. Esses são em colaboração com os professores doutores: Ricardo M. Ribeiro e Andrés P. L. Barbero, da Pós-Graduação em Instrumentação e Ótica Aplicada e Tadeu F. Nagashima, Vanessa P. R. Magri da Pós-Graduação em Eng. Elétrica e de Telecomunicações e Luiz A. Neto da Orange Telecom",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Fundação Carlos Chagas Filho de Amparo à Pesquisa do Estado do RJ",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Luiz Anet Neto", "Ricardo Marque Ribeiro", "Andres Pablo Lopez Barbero", "Vanessa Magri", "Tadeu Nagashima Ferreira", "Carlos Rodrigues Pereira", "Gustavo Bastos Lyra", "Sorele Batista Fiaux", "Fernando Cunha Peixoto"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p20",
    titulo:      "DESENVOLVIMENTO DO LOTE PIONEIRO DO SISTEMA INTELIGENTE DE MONITORAMENTO DE DESCARGAS PARCIAIS PARA TRANSFORMADORES DE POTÊNCIA",
    status:      "completed",
    tipo:        "rd",
    periodo:     "2019–2021",
    resumo:      "O sistema inteligente de monitoramento de descargas parciais permitirá a medição e análise confiável das vibrações que ocorrem no interior de equipamentos elétricos, com objetivo de detectar defeitos ",
    descricao:   "O sistema inteligente de monitoramento de descargas parciais permitirá a medição e análise confiável das vibrações que ocorrem no interior de equipamentos elétricos, com objetivo de detectar defeitos no sistema de isolamento destes ativos elétricos, diagnosticar e indicar ações de manutenção corretiva, antes que um dano maior ou uma avaria ocorra. A utilização desta nova tecnologia visa aA eliminação de riscos de pessoal na manutenção e operação, eliminação de perdas de ativos e receitas,; melhoria da disponibilidade das instalações,; a eliminaçãor riscos ambientais, além da redução dos prêmios de seguro. Dessa forma o escopo do Projeto: Lote pioneiro consiste em uma plataforma para geração de tecnologias inovadoras passíveis de proteção por patente, em que a nova propriedade intelectual será compartilhada com a Eletronorte, Tracel e UFF",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Não especificado",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Henrique O. Henriques (Coordenador)", "Andres Pablo Lopez Barbero"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p21",
    titulo:      "Proposta para Formação de Turmas de Pós-Graduação Stricto Sensu em Engenharia Elétrica e de Telecomunicações (Minter/Dinter)",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2019–2019",
    resumo:      "Curso em nível de mestrado e doutorado no formato Minter/Dinter ao Instituto Federal Fluminense atendendo a demanda exposta no edital IFF No 184 ? Minter/Dinter.&#10;&#10;Projeto aprovado, mas não efe",
    descricao:   "Curso em nível de mestrado e doutorado no formato Minter/Dinter ao Instituto Federal Fluminense atendendo a demanda exposta no edital IFF No 184 ? Minter/Dinter.&#10;&#10;Projeto aprovado, mas não efetivado devido ao corte de recursos pelo governo federal.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Instituto Federal Fluminense",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Andres Pablo Lopez Barbero", "MEDEIROS, DIANNE S. V.", "Hypolito José Kalinowski", "Vitor Hugo Ferreira", "Pedro Vladimir Gonzalez Castellanos", "Guilherme Goncalves Sotelo", "Natalia Castro Fernandes", "Diogo Menezes Ferrazani Mattos", "José Andrés Santisteban"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p22",
    titulo:      "Dispositivos, Antenas e Caracterização do Canal de Comunicação para Ondas Milimétricas",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2019–2024",
    resumo:      "Este projeto prevê o financiamento de pesquisa na criação e análise de circuitos impressos com função de dispositivos e antenas para a faixa de microondas. Além disso, também prevê financiamento para ",
    descricao:   "Este projeto prevê o financiamento de pesquisa na criação e análise de circuitos impressos com função de dispositivos e antenas para a faixa de microondas. Além disso, também prevê financiamento para equipamentos utilizados na caracterização do canal de comunicação na faixa de microoondas. No projeto há pesquisadores da linha de pesquisa Sinais e Sistemas de Comunicações Móveis do PPGEET/UFF, ligados ao Laboratório de Antenas e Propagação (LAProp) da UFF. Também está presente o professor Vinicius N H Silva do PPGEET/UFF e PPGIO/UFF e CEFET, ligado ao Laboratório de Comunicações Ópticas (LaCOp) da UFF",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Fundação Carlos Chagas Filho de Amparo à Pesquisa do Estado do RJ",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "VANESSA MAGRI", "Leni Joaquim de Matos", "Tadeu Nagashima Ferreira (Coordenador)", "Pedro Vladimir Gonzalez Castellanos", "Mauricio Weber Benjó Silva"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p23",
    titulo:      "Rastreador Inteligente de Ligações Irregulares",
    status:      "completed",
    tipo:        "rd",
    periodo:     "2019–2021",
    resumo:      "Desenvolver equipamento capaz de rastrear ligações clandestinas em ramais de ligação de clientes de baixa tensão, composto de módulo fonte (transmissor) e módulo carga (receptor) que registra a difere",
    descricao:   "Desenvolver equipamento capaz de rastrear ligações clandestinas em ramais de ligação de clientes de baixa tensão, composto de módulo fonte (transmissor) e módulo carga (receptor) que registra a diferença em Watts entre a energia fornecida e a energia faturada em um cliente, evidenciando se há furto por desvio clandestino dentro da entrada de energia para o cliente, objetivando-se a redução de perdas comerciais por detecção de fraude nas inspeções realizadas pela concessionária",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "LIGHT Serviços de Eletricidade",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Henrique O. Henriques", "Andres Pablo Lopez Barbero (Coordenador)"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p24",
    titulo:      "Implantação de um Ambiente Coworking para StartUps e Capacitação na área de Bebidas Fermentadas",
    status:      "completed",
    tipo:        "rd",
    periodo:     "2020–2024",
    resumo:      "Ambiente colaborativo multitarefas voltados para nucleação de novos negócios bem como para pesquisa, desenvolvimento e capacitação de recursos humanos na área de bebidas fermentadas para crescimento e",
    descricao:   "Ambiente colaborativo multitarefas voltados para nucleação de novos negócios bem como para pesquisa, desenvolvimento e capacitação de recursos humanos na área de bebidas fermentadas para crescimento econômico e industrial da cidade de Niterói. Como objetos concretos desta proposta destacam-se, mas não de forma exclusiva, a construção de uma unidade protótipo de produção de mostos cervejeiros adequada a atender à demanda criada pela Lei Municipal no 3288 de 10 de maio de 2017 (conforme já esmiuçado no item 1 desta proposta). Essa unidade deverá atender a requisitos de baixo custo e simplicidade de operação para que os bares de Niterói pequenos e médios possam criar e executar suas próprias receitas. Vale observar, que o desenvolvimento de um protótipo de simples operação não significa que o mesmo será rudimentar. Assim, projetos de pesquisa e desenvolvimento tecnológico serão desenvolvidos em paralelo no intuito agregar valor a unidade protótipo que, posteriormente, também será utilizada como ferramenta para novos estudos. Por fim, mas não menos importante, não basta somente um equipamento. Existe intrinsecamente uma necessidade de, junto ao desenvolvimento tecnológico, fomentar os recursos humanos da cidade de Niterói. Com isso, outro objeto do projeto envolve o oferecimento de cursos de capacitação, na área de processos, utilizando a unidade protótipo, na área de microbiologia industrial, voltados para o a manutenção e operação de inóculos especiais, e na área de processos de produção de bebidas fermentadas. Cabe salientar que a unidade protótipo será construída junto a uma empresa a ser implementada, e a capacitação servirá como um importante apoio a empreendedores locais interessados em negócios na área de bebidas fermentadas.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Prefeitura Municipal de Niterói",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Andres Pablo Lopez Barbero", "Sorele Batista Fiaux", "Leandro Alcoforado Sphaier", "Fernando Cunha Peixoto", "Flávia Ferreira de Carvalho Marques"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p25",
    titulo:      "Rio de Janeiro 4.0: Sistema de Monitoramento, Sensoriamento e Segurança da Informação para Pequenos e Médios Agricultores",
    status:      "ongoing",
    tipo:        "academic",
    periodo:     "2019–atual",
    resumo:      "O rápido crescimento da tecnologia, eletrônica e de comunicações, tem facilitado a automação e monitoramento dos processos. Desta forma, o desenvolvimento de redes de dispositivos de comunicação sem f",
    descricao:   "O rápido crescimento da tecnologia, eletrônica e de comunicações, tem facilitado a automação e monitoramento dos processos. Desta forma, o desenvolvimento de redes de dispositivos de comunicação sem fio com capacidade para coletar informações de diversos tipos tem atraído a atenção de muitos pesquisadores com o objetivo de otimizar os processos de produção e facilitar a vida das pessoas. A estrutura deste tipo de redes de sensores, vá em convergência com a definição da Internet das Coisas (Internet of Things - IoT). Tipicamente uma rede de sensores é definida como uma rede de nós que trabalham de forma cooperativa e enviam informações do ambiente onde se encontram através de sensores. Uma forma de integrar os benefícios e funcionalidades deste tipo de tecnologia e outras áreas interdisciplinares com o objetivo de otimizar a produção agrícola, é o que hoje é conhecido como Agricultura 4.0. Esta nova etapa de evolução não depende simplesmente na aplicação de fertilizantes, irrigação, agrotóxicos de forma indiscriminada, mas sim aplicar estes recursos de forma controlada, em menor quantidade e em áreas especificas do cultivo. Por outro lado, as informações coletadas devem ser armazenadas e processada a fim de construir modelos que permita definir com antecedência estratégias futuras. Para atingir estes objetivos, pesquisadores de diversas áreas devem trabalhar em conjunto de forma a integrar a expertise de cada um para criar soluções tecnológicas aos problemas encontrados. No projeto atual, um conjunto de pesquisadores de duas universidades federais tem como objetivo o desenvolvimento de uma rede de sensores do tipo IoT com o objetivo de monitorar uma serie de magnitudes físicas como temperatura, pressão, taxa de precipitação, pragas, etc, e assim poder estabelecer estratégias para otimizar a produção agrícola e facilitar a vida dos agricultores. Neste contexto diversas soluções como estações meteorológicas, sensoriamento remoto com o uso de veículos não tripulados, armazenamento e processamento de dados coletados serão implementados.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Fundação Carlos Chagas Filho de Amparo à Pesquisa do Estado do RJ",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Leni Joaquim de Matos", "Tadeu Nagashima Ferreira", "Pedro Vladimir Gonzalez Castellanos", "Diogo Menezes Ferrazani Mattos", "Vanessa Przybylski Ribeiro Magri", "Dianne Scherly Varela de Medeiros", "Alberto Gaspar Guimarães", "Henderson Silva Wanderley"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p26",
    titulo:      "Instrumentação, Sensoriamento e Monitoramento no Ambito da Agricultura e Pecuária 4.0 - ISMAAP 4.0",
    status:      "ongoing",
    tipo:        "academic",
    periodo:     "2023–atual",
    resumo:      "Com a crescente demanda mundial por alimentos, o Brasil destaca-se na produção de proteína animal e vegetal, enfrentando desafios ambientais pelos impactos gerados. A emissão de gases de efeito estufa",
    descricao:   "Com a crescente demanda mundial por alimentos, o Brasil destaca-se na produção de proteína animal e vegetal, enfrentando desafios ambientais pelos impactos gerados. A emissão de gases de efeito estufa (GEE) e óxidos nitrosos requer monitoramento das atividades agropecuárias para avaliar sua sustentabilidade e buscar soluções de mitigação. Tecnologias digitais como sensoriamento remoto, internet das coisas e computação em nuvem são amplamente utilizadas, contribuindo para o diagnóstico da produtividade e parâmetros biofísicos, e permitindo o monitoramento da terra, recursos naturais, índices zootécnicos e segurança alimentar. No entanto, a instalação de sensores complexos não é suficiente para o desenvolvimento sustentável, pois podem gerar grandes volumes de dados de difícil acesso, afastando a tecnologia dos produtores. Além disso, áreas agropecuárias isoladas e a falta de sistemas de telecomunicações locais criam dificuldades adicionais na conexão entre sensores e sistemas de monitoramento e o produtor. É necessário desenvolver um sistema adequado para as condições de campo, com técnicas de comunicação e extração de dados em um sistema de fácil leitura, a fim de auxiliar o produtor em seu trabalho. Os dados coletados podem ser armazenados para estudos posteriores, incluindo a elaboração de modelos de taxa de crescimento, otimização de projetos de irrigação, estado nutricional e físico do solo, e condições climáticas favoráveis aos cultivos.O objetivo do projeto é desenvolver uma estação multi-paramétrica com comunicação híbrida e computação em nuvem, um sistema de auxílio à tomada de decisão para o produtor, uma estação de fluxo de calor óptico para avaliação de evapotranspiração e GEE, e um sistema de câmeras com inteligência artificial embarcada para observação e avaliação de comportamento animal a distância.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Conselho Nacional de Desenvolvimento Científico e Tecnológico",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Luiz Anet Neto", "Carlos Rodrigues Pereira", "Gustavo Bastos Lyra", "Hani Al HAJJAR", "Argemiro Sanavria", "Elisa Cristina Modesto", "Fernando Luiz de Carvalho e Silva", "Marcel Carvalho Abreu", "Mariana de Oliveira Pereira", "Mauro Antonio Homem Antunes", "Ricardo Vilar Neves", "Tatiana Pires Pereira", "Thiago Vieira Nogueira Coelho"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p27",
    titulo:      "Sistemas de Comunicação Ótica Sem Fio para Suporte ao Acesso de Banda Larga",
    status:      "ongoing",
    tipo:        "academic",
    periodo:     "2025–atual",
    resumo:      "Este projeto foca no desenvolvimento de tecnologias para comunicação sem fio utilizando Comunicação por Luz Visível (VLC, do inglês &quot;Visible Light Communication&quot;) e Comunicação Óptica em Esp",
    descricao:   "Este projeto foca no desenvolvimento de tecnologias para comunicação sem fio utilizando Comunicação por Luz Visível (VLC, do inglês &quot;Visible Light Communication&quot;) e Comunicação Óptica em Espaço Livre (FSO, do inglês &quot;Free-Space Optical Communication&quot;). O objetivo é melhorar a capacidade, eficiência e confiabilidade dessas tecnologias de comunicação para a próxima geração de redes de comunicações móveis (6G). VLC e FSO são vistas como soluções potenciais para superar as limitações dos sistemas sem fio tradicionais, especialmente no contexto de aplicações emergentes como Realidade Aumentada, Internet das Coisas (IoT) e Sistemas de Transporte Inteligente. O Projeto pretende aprimorar as capacidades dos enlaces VLC e FSO por meio de abordagens teóricas e experimentais, com foco em técnicas de acesso múltiplo, aprendizado de máquina, protocolos adaptativos, antenas ópticas, entre outros. O projeto pretende explorar o potencial da VLC para fornecer, simultaneamente, comunicação de dados e iluminação. Com esse objetivo pretende-se aumentar a largura de banda limitada pela modulação e a potência óptica máxima dos LEDs através da técnica de múltiplo acesso com Divisão de Taxas (RSMA). Nesse cenário é também importante implementar antenas ópticas para ampliar o campo de visão do sistema. Já para FSO, uma vez que é suscetível a condições atmosféricas e obstáculos, pretende-se aqui enfrentar esses desafios desenvolvendo técnicas de rastreamento de feixe óptico usando algoritmos de aprendizado de máquina, especificamente Redes Neurais Artificiais (RNA). Além disso, desenvolver em conjunto um sistema LIDAR que agrega ao sistema de comunicação uma capacidade de sensoriamento, importante para aplicação de comunicação veicular e detecção de pessoas.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Conselho Nacional de Desenvolvimento Científico e Tecnológico",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Andres Pablo Lopez Barbero", "Hypolito José Kalinowski", "Maria do Carmo Raposo de Medeiros", "Paulo Miguel Nepomuceno Pereira Monteiro", "Fernando Pedro Pereira Guioma", "Roberto Brauer Di Renna", "Paulo André"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p28",
    titulo:      "Implementação de Ações de Segurança em Fazendas Solares",
    status:      "completed",
    tipo:        "rd",
    periodo:     "2024–2024",
    resumo:      "O presente projeto visa enfrentar o desafio crescente de segurança em áreas remotas e vulneráveis, como fazendas solares, por meio do desenvolvimento de um sistema de detecção baseado em interferometr",
    descricao:   "O presente projeto visa enfrentar o desafio crescente de segurança em áreas remotas e vulneráveis, como fazendas solares, por meio do desenvolvimento de um sistema de detecção baseado em interferometria óptica distribuída. Com base em tecnologias de ponta e na expertise do grupo de pesquisa da UFF, foi estabelecida uma parceria com a empresa AEON para viabilizar a construção de um protótipo funcional, sua validação experimental e sua posterior replicação e apresentação ao mercado. A relevância da proposta reside na inovação do método de detecção, no potencial de aplicação industrial imediata e na contribuição para a soberania tecnológica nacional no setor de segurança.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Não especificado",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva (Coordenador)", "Alexander Carneiro", "Andrés Pablo Lopez Barbero", "Matheus de Souza Perdigão Silva"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p29",
    titulo:      "Desenvolvimento de um Sensor Óptico de Uumidade do Solo e do Ar",
    status:      "ongoing",
    tipo:        "academic",
    periodo:     "2025–atual",
    resumo:      "A dinâmica da água no solo é fundamental para a agricultura, influenciando práticas como a irrigação, a aplicação de produtos fitofarmacêuticos, a gestão de nutrientes e a previsão de colheitas. A mon",
    descricao:   "A dinâmica da água no solo é fundamental para a agricultura, influenciando práticas como a irrigação, a aplicação de produtos fitofarmacêuticos, a gestão de nutrientes e a previsão de colheitas. A monitorização da humidade do ar no solo a diferentes profundidades e sob diversas condições é essencial para garantir a sustentabilidade agrícola e a eficiência na utilização dos recursos hídricos. Este projeto propõe o desenvolvimento de um sensor de umidade do ar e/ou solo baseado na utilização de uma fibra óptica, equipado principalmente em sua extremidade com uma sonda de medição sensível à água (ponta do sensor de fibra óptica), utilizando materiais inovadores (extensível, hidrofílico, translúcido, etc.) e tecnologia de impressão 3D de resolução micrométrica por fotopolimerização de dois fótons (através do uso da impressora Nanoscribe).",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Não especificado",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Hani Al HAJJAR (Coordenador)", "Muneeb Ullah Khan"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
  {
    id:          "p30",
    titulo:      "Sistema integrado de Comunicações e Lidar",
    status:      "completed",
    tipo:        "academic",
    periodo:     "2018–2022",
    resumo:      "The LANDmaRk project targets the integration of LIDAR and optical wireless&#10;communication technologies within the same systems or devices for the future Internet&#10;of Things (IoT), including Cybe",
    descricao:   "The LANDmaRk project targets the integration of LIDAR and optical wireless&#10;communication technologies within the same systems or devices for the future Internet&#10;of Things (IoT), including Cyber-Physical Systems (CPS), such autonomous vehicles.&#10;Apart from the cost and size reduction, the integration of the two technologies brings&#10;further benefits. Namely, the communication domain complements the LiDAR domain&#10;information to enable the formation of higher resolution scene imagery, and the&#10;LiDAR domain is instrumental for the establishment, coordination and maintenance&#10;of high capacity wireless communication links. LANDmaRk will provide the fusion of&#10;communication and optical reflectometry, with fast high resolution mapping and high&#10;speed communication links to support vehicles sharing of multi-gigabit data about the&#10;surrounding environment and recognizing objects in real time. Therefore, vehicles are&#10;able to determine the optimal driving strategy collaboratively.",
    pi:          "Vinicius Nunes Henrique Silva",
    fomento:     "Fundação para a Ciência e a Tecnologia",
    progresso:   50,
    equipe:      ["Vinicius Nunes Henrique Silva", "Maria do Carmo Raposo de Medeiros (Coordenador)", "Paulo Miguel Nepomuceno Pereira Monteiro", "Henrique Jose Almeida Silva", "Atílio Manuel da Silva Gameiro", "Luis Alberto da Silva Cruz", "Ana Maria Sousa da Rocha"],
    tags:        [],
    objetivos:   [],
    metodologia: "",
    resultados:  [],
    publicacoes: [],
  },
];

// ── PATENTES ───────────────────────────────────────────────
const PATENTES = [
  {
    emoji:  "📋",
    titulo: "DISPOSITIVO ÓTICO PARA DETERMINAÇÃO DA VIABILIDADE CELULAR ATRAVÉS DA REDUÇÃO DO AZUL DE METILENO",
    numero: "2018",
    status: "pending",
  },
];

// ── PARCEIROS ──────────────────────────────────────────────
const PARCEIROS = {
  fomento:    ["CNPq", "FAPERJ", "FINEP", "ANEEL P&D", "CAPES"],
  industrial: ["Adicionar parceiros industriais aqui"],
  academico:  ["Adicionar colaborações acadêmicas aqui"],
};
